require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TexturesController do

  # This should return the minimal set of attributes required to create a valid
  # Texture. As you add validations to Texture, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all textures as @textures" do
      texture = Texture.create! valid_attributes
      get :index
      assigns(:textures).should eq([texture])
    end
  end

  describe "GET show" do
    it "assigns the requested texture as @texture" do
      texture = Texture.create! valid_attributes
      get :show, :id => texture.id.to_s
      assigns(:texture).should eq(texture)
    end
  end

  describe "GET new" do
    it "assigns a new texture as @texture" do
      get :new
      assigns(:texture).should be_a_new(Texture)
    end
  end

  describe "GET edit" do
    it "assigns the requested texture as @texture" do
      texture = Texture.create! valid_attributes
      get :edit, :id => texture.id.to_s
      assigns(:texture).should eq(texture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Texture" do
        expect {
          post :create, :texture => valid_attributes
        }.to change(Texture, :count).by(1)
      end

      it "assigns a newly created texture as @texture" do
        post :create, :texture => valid_attributes
        assigns(:texture).should be_a(Texture)
        assigns(:texture).should be_persisted
      end

      it "redirects to the created texture" do
        post :create, :texture => valid_attributes
        response.should redirect_to(Texture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved texture as @texture" do
        # Trigger the behavior that occurs when invalid params are submitted
        Texture.any_instance.stub(:save).and_return(false)
        post :create, :texture => {}
        assigns(:texture).should be_a_new(Texture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Texture.any_instance.stub(:save).and_return(false)
        post :create, :texture => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested texture" do
        texture = Texture.create! valid_attributes
        # Assuming there are no other textures in the database, this
        # specifies that the Texture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Texture.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => texture.id, :texture => {'these' => 'params'}
      end

      it "assigns the requested texture as @texture" do
        texture = Texture.create! valid_attributes
        put :update, :id => texture.id, :texture => valid_attributes
        assigns(:texture).should eq(texture)
      end

      it "redirects to the texture" do
        texture = Texture.create! valid_attributes
        put :update, :id => texture.id, :texture => valid_attributes
        response.should redirect_to(texture)
      end
    end

    describe "with invalid params" do
      it "assigns the texture as @texture" do
        texture = Texture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Texture.any_instance.stub(:save).and_return(false)
        put :update, :id => texture.id.to_s, :texture => {}
        assigns(:texture).should eq(texture)
      end

      it "re-renders the 'edit' template" do
        texture = Texture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Texture.any_instance.stub(:save).and_return(false)
        put :update, :id => texture.id.to_s, :texture => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested texture" do
      texture = Texture.create! valid_attributes
      expect {
        delete :destroy, :id => texture.id.to_s
      }.to change(Texture, :count).by(-1)
    end

    it "redirects to the textures list" do
      texture = Texture.create! valid_attributes
      delete :destroy, :id => texture.id.to_s
      response.should redirect_to(textures_url)
    end
  end

end
